// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_expectile_forward
NumericVector cpp_expectile_forward(NumericVector tau, Function phi, Function survival, double mean, double tol, int max_iter);
RcppExport SEXP _distionary_cpp_expectile_forward(SEXP tauSEXP, SEXP phiSEXP, SEXP survivalSEXP, SEXP meanSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< Function >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Function >::type survival(survivalSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_expectile_forward(tau, phi, survival, mean, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// cpp_expectile_reverse_cdf
NumericVector cpp_expectile_reverse_cdf(NumericVector at, Function expectile, double mean, double tol, int max_iter);
RcppExport SEXP _distionary_cpp_expectile_reverse_cdf(SEXP atSEXP, SEXP expectileSEXP, SEXP meanSEXP, SEXP tolSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type at(atSEXP);
    Rcpp::traits::input_parameter< Function >::type expectile(expectileSEXP);
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_expectile_reverse_cdf(at, expectile, mean, tol, max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_distionary_cpp_expectile_forward", (DL_FUNC) &_distionary_cpp_expectile_forward, 6},
    {"_distionary_cpp_expectile_reverse_cdf", (DL_FUNC) &_distionary_cpp_expectile_reverse_cdf, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_distionary(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
