# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_expectile_forward <- function(tau, phi, survival, mean, tol, max_iter) {
    .Call(`_distionary_cpp_expectile_forward`, tau, phi, survival, mean, tol, max_iter)
}

cpp_expectile_reverse_cdf <- function(at, expectile, mean, tol, max_iter) {
    .Call(`_distionary_cpp_expectile_reverse_cdf`, at, expectile, mean, tol, max_iter)
}

